// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	domain "ultrathreads/internal/domain"
	service "ultrathreads/internal/service"

	gomock "github.com/golang/mock/gomock"
)

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// CreateSchool mocks base method.
func (m *MockUsers) CreateSchool(ctx context.Context, userID uint, schoolName string) (domain.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchool", ctx, userID, schoolName)
	ret0, _ := ret[0].(domain.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchool indicates an expected call of CreateSchool.
func (mr *MockUsersMockRecorder) CreateSchool(ctx, userID, schoolName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchool", reflect.TypeOf((*MockUsers)(nil).CreateSchool), ctx, userID, schoolName)
}

// RefreshTokens mocks base method.
func (m *MockUsers) RefreshTokens(ctx context.Context, refreshToken string) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, refreshToken)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockUsersMockRecorder) RefreshTokens(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockUsers)(nil).RefreshTokens), ctx, refreshToken)
}

// SignIn mocks base method.
func (m *MockUsers) SignIn(ctx context.Context, input service.UserSignInInput) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, input)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockUsersMockRecorder) SignIn(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockUsers)(nil).SignIn), ctx, input)
}

// SignUp mocks base method.
func (m *MockUsers) SignUp(ctx context.Context, input service.UserSignUpInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUsersMockRecorder) SignUp(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUsers)(nil).SignUp), ctx, input)
}

// Verify mocks base method.
func (m *MockUsers) Verify(ctx context.Context, userID uint, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, userID, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockUsersMockRecorder) Verify(ctx, userID, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockUsers)(nil).Verify), ctx, userID, hash)
}

// MockSchools is a mock of Schools interface.
type MockSchools struct {
	ctrl     *gomock.Controller
	recorder *MockSchoolsMockRecorder
}

// MockSchoolsMockRecorder is the mock recorder for MockSchools.
type MockSchoolsMockRecorder struct {
	mock *MockSchools
}

// NewMockSchools creates a new mock instance.
func NewMockSchools(ctrl *gomock.Controller) *MockSchools {
	mock := &MockSchools{ctrl: ctrl}
	mock.recorder = &MockSchoolsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchools) EXPECT() *MockSchoolsMockRecorder {
	return m.recorder
}

// ConnectFondy mocks base method.
func (m *MockSchools) ConnectFondy(ctx context.Context, input service.ConnectFondyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectFondy", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectFondy indicates an expected call of ConnectFondy.
func (mr *MockSchoolsMockRecorder) ConnectFondy(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectFondy", reflect.TypeOf((*MockSchools)(nil).ConnectFondy), ctx, input)
}

// ConnectSendPulse mocks base method.
func (m *MockSchools) ConnectSendPulse(ctx context.Context, input service.ConnectSendPulseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectSendPulse", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectSendPulse indicates an expected call of ConnectSendPulse.
func (mr *MockSchoolsMockRecorder) ConnectSendPulse(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectSendPulse", reflect.TypeOf((*MockSchools)(nil).ConnectSendPulse), ctx, input)
}

// Create mocks base method.
func (m *MockSchools) Create(ctx context.Context, name string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSchoolsMockRecorder) Create(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSchools)(nil).Create), ctx, name)
}

// GetByDomain mocks base method.
func (m *MockSchools) GetByDomain(ctx context.Context, domainName string) (domain.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomain", ctx, domainName)
	ret0, _ := ret[0].(domain.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomain indicates an expected call of GetByDomain.
func (mr *MockSchoolsMockRecorder) GetByDomain(ctx, domainName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomain", reflect.TypeOf((*MockSchools)(nil).GetByDomain), ctx, domainName)
}

// GetById mocks base method.
func (m *MockSchools) GetById(ctx context.Context, id uint) (domain.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(domain.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockSchoolsMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockSchools)(nil).GetById), ctx, id)
}

// UpdateSettings mocks base method.
func (m *MockSchools) UpdateSettings(ctx context.Context, schoolID uint, input domain.UpdateSchoolSettingsInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, schoolID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSchoolsMockRecorder) UpdateSettings(ctx, schoolID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSchools)(nil).UpdateSettings), ctx, schoolID, input)
}

// MockStudents is a mock of Students interface.
type MockStudents struct {
	ctrl     *gomock.Controller
	recorder *MockStudentsMockRecorder
}

// MockStudentsMockRecorder is the mock recorder for MockStudents.
type MockStudentsMockRecorder struct {
	mock *MockStudents
}

// NewMockStudents creates a new mock instance.
func NewMockStudents(ctrl *gomock.Controller) *MockStudents {
	mock := &MockStudents{ctrl: ctrl}
	mock.recorder = &MockStudentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudents) EXPECT() *MockStudentsMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockStudents) GetById(ctx context.Context, schoolID, id uint) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, schoolID, id)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockStudentsMockRecorder) GetById(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockStudents)(nil).GetById), ctx, schoolID, id)
}

// GetBySchool mocks base method.
func (m *MockStudents) GetBySchool(ctx context.Context, schoolID uint, query domain.GetStudentsQuery) ([]domain.Student, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchool", ctx, schoolID, query)
	ret0, _ := ret[0].([]domain.Student)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBySchool indicates an expected call of GetBySchool.
func (mr *MockStudentsMockRecorder) GetBySchool(ctx, schoolID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchool", reflect.TypeOf((*MockStudents)(nil).GetBySchool), ctx, schoolID, query)
}

// GetLesson mocks base method.
func (m *MockStudents) GetLesson(ctx context.Context, studentID, lessonID uint) (domain.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLesson", ctx, studentID, lessonID)
	ret0, _ := ret[0].(domain.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLesson indicates an expected call of GetLesson.
func (mr *MockStudentsMockRecorder) GetLesson(ctx, studentID, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLesson", reflect.TypeOf((*MockStudents)(nil).GetLesson), ctx, studentID, lessonID)
}

// GetModuleContent mocks base method.
func (m *MockStudents) GetModuleContent(ctx context.Context, schoolID, studentID, moduleID uint) (domain.ModuleContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleContent", ctx, schoolID, studentID, moduleID)
	ret0, _ := ret[0].(domain.ModuleContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleContent indicates an expected call of GetModuleContent.
func (mr *MockStudentsMockRecorder) GetModuleContent(ctx, schoolID, studentID, moduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleContent", reflect.TypeOf((*MockStudents)(nil).GetModuleContent), ctx, schoolID, studentID, moduleID)
}

// GiveAccessToOffer mocks base method.
func (m *MockStudents) GiveAccessToOffer(ctx context.Context, studentID uint, offer domain.Offer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GiveAccessToOffer", ctx, studentID, offer)
	ret0, _ := ret[0].(error)
	return ret0
}

// GiveAccessToOffer indicates an expected call of GiveAccessToOffer.
func (mr *MockStudentsMockRecorder) GiveAccessToOffer(ctx, studentID, offer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveAccessToOffer", reflect.TypeOf((*MockStudents)(nil).GiveAccessToOffer), ctx, studentID, offer)
}

// RefreshTokens mocks base method.
func (m *MockStudents) RefreshTokens(ctx context.Context, schoolID uint, refreshToken string) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, schoolID, refreshToken)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockStudentsMockRecorder) RefreshTokens(ctx, schoolID, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockStudents)(nil).RefreshTokens), ctx, schoolID, refreshToken)
}

// RemoveAccessToOffer mocks base method.
func (m *MockStudents) RemoveAccessToOffer(ctx context.Context, studentID uint, offer domain.Offer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccessToOffer", ctx, studentID, offer)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccessToOffer indicates an expected call of RemoveAccessToOffer.
func (mr *MockStudentsMockRecorder) RemoveAccessToOffer(ctx, studentID, offer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccessToOffer", reflect.TypeOf((*MockStudents)(nil).RemoveAccessToOffer), ctx, studentID, offer)
}

// SetLessonFinished mocks base method.
func (m *MockStudents) SetLessonFinished(ctx context.Context, studentID, lessonID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLessonFinished", ctx, studentID, lessonID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLessonFinished indicates an expected call of SetLessonFinished.
func (mr *MockStudentsMockRecorder) SetLessonFinished(ctx, studentID, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLessonFinished", reflect.TypeOf((*MockStudents)(nil).SetLessonFinished), ctx, studentID, lessonID)
}

// SignIn mocks base method.
func (m *MockStudents) SignIn(ctx context.Context, input service.SchoolSignInInput) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, input)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockStudentsMockRecorder) SignIn(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockStudents)(nil).SignIn), ctx, input)
}

// SignUp mocks base method.
func (m *MockStudents) SignUp(ctx context.Context, input service.StudentSignUpInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockStudentsMockRecorder) SignUp(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockStudents)(nil).SignUp), ctx, input)
}

// Verify mocks base method.
func (m *MockStudents) Verify(ctx context.Context, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockStudentsMockRecorder) Verify(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockStudents)(nil).Verify), ctx, hash)
}

// MockStudentLessons is a mock of StudentLessons interface.
type MockStudentLessons struct {
	ctrl     *gomock.Controller
	recorder *MockStudentLessonsMockRecorder
}

// MockStudentLessonsMockRecorder is the mock recorder for MockStudentLessons.
type MockStudentLessonsMockRecorder struct {
	mock *MockStudentLessons
}

// NewMockStudentLessons creates a new mock instance.
func NewMockStudentLessons(ctrl *gomock.Controller) *MockStudentLessons {
	mock := &MockStudentLessons{ctrl: ctrl}
	mock.recorder = &MockStudentLessonsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentLessons) EXPECT() *MockStudentLessonsMockRecorder {
	return m.recorder
}

// AddFinished mocks base method.
func (m *MockStudentLessons) AddFinished(ctx context.Context, studentID, lessonID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFinished", ctx, studentID, lessonID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFinished indicates an expected call of AddFinished.
func (mr *MockStudentLessonsMockRecorder) AddFinished(ctx, studentID, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFinished", reflect.TypeOf((*MockStudentLessons)(nil).AddFinished), ctx, studentID, lessonID)
}

// SetLastOpened mocks base method.
func (m *MockStudentLessons) SetLastOpened(ctx context.Context, studentID, lessonID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastOpened", ctx, studentID, lessonID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastOpened indicates an expected call of SetLastOpened.
func (mr *MockStudentLessonsMockRecorder) SetLastOpened(ctx, studentID, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastOpened", reflect.TypeOf((*MockStudentLessons)(nil).SetLastOpened), ctx, studentID, lessonID)
}

// MockAdmins is a mock of Admins interface.
type MockAdmins struct {
	ctrl     *gomock.Controller
	recorder *MockAdminsMockRecorder
}

// MockAdminsMockRecorder is the mock recorder for MockAdmins.
type MockAdminsMockRecorder struct {
	mock *MockAdmins
}

// NewMockAdmins creates a new mock instance.
func NewMockAdmins(ctrl *gomock.Controller) *MockAdmins {
	mock := &MockAdmins{ctrl: ctrl}
	mock.recorder = &MockAdminsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmins) EXPECT() *MockAdminsMockRecorder {
	return m.recorder
}

// CreateStudent mocks base method.
func (m *MockAdmins) CreateStudent(ctx context.Context, inp domain.CreateStudentInput) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudent", ctx, inp)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudent indicates an expected call of CreateStudent.
func (mr *MockAdminsMockRecorder) CreateStudent(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudent", reflect.TypeOf((*MockAdmins)(nil).CreateStudent), ctx, inp)
}

// DeleteStudent mocks base method.
func (m *MockAdmins) DeleteStudent(ctx context.Context, schoolID, studentID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudent", ctx, schoolID, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudent indicates an expected call of DeleteStudent.
func (mr *MockAdminsMockRecorder) DeleteStudent(ctx, schoolID, studentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudent", reflect.TypeOf((*MockAdmins)(nil).DeleteStudent), ctx, schoolID, studentID)
}

// GetCourseById mocks base method.
func (m *MockAdmins) GetCourseById(ctx context.Context, schoolID, courseID uint) (domain.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourseById", ctx, schoolID, courseID)
	ret0, _ := ret[0].(domain.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourseById indicates an expected call of GetCourseById.
func (mr *MockAdminsMockRecorder) GetCourseById(ctx, schoolID, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourseById", reflect.TypeOf((*MockAdmins)(nil).GetCourseById), ctx, schoolID, courseID)
}

// GetCourses mocks base method.
func (m *MockAdmins) GetCourses(ctx context.Context, schoolID uint) ([]domain.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourses", ctx, schoolID)
	ret0, _ := ret[0].([]domain.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourses indicates an expected call of GetCourses.
func (mr *MockAdminsMockRecorder) GetCourses(ctx, schoolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourses", reflect.TypeOf((*MockAdmins)(nil).GetCourses), ctx, schoolID)
}

// RefreshTokens mocks base method.
func (m *MockAdmins) RefreshTokens(ctx context.Context, schoolID uint, refreshToken string) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, schoolID, refreshToken)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAdminsMockRecorder) RefreshTokens(ctx, schoolID, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAdmins)(nil).RefreshTokens), ctx, schoolID, refreshToken)
}

// SignIn mocks base method.
func (m *MockAdmins) SignIn(ctx context.Context, input service.SchoolSignInInput) (service.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, input)
	ret0, _ := ret[0].(service.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAdminsMockRecorder) SignIn(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAdmins)(nil).SignIn), ctx, input)
}

// UpdateStudent mocks base method.
func (m *MockAdmins) UpdateStudent(ctx context.Context, inp domain.UpdateStudentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudent", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudent indicates an expected call of UpdateStudent.
func (mr *MockAdminsMockRecorder) UpdateStudent(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudent", reflect.TypeOf((*MockAdmins)(nil).UpdateStudent), ctx, inp)
}

// MockFiles is a mock of Files interface.
type MockFiles struct {
	ctrl     *gomock.Controller
	recorder *MockFilesMockRecorder
}

// MockFilesMockRecorder is the mock recorder for MockFiles.
type MockFilesMockRecorder struct {
	mock *MockFiles
}

// NewMockFiles creates a new mock instance.
func NewMockFiles(ctrl *gomock.Controller) *MockFiles {
	mock := &MockFiles{ctrl: ctrl}
	mock.recorder = &MockFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiles) EXPECT() *MockFilesMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockFiles) GetByID(ctx context.Context, id, schoolID uint) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, schoolID)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFilesMockRecorder) GetByID(ctx, id, schoolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFiles)(nil).GetByID), ctx, id, schoolID)
}

// InitStorageUploaderWorkers mocks base method.
func (m *MockFiles) InitStorageUploaderWorkers(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitStorageUploaderWorkers", ctx)
}

// InitStorageUploaderWorkers indicates an expected call of InitStorageUploaderWorkers.
func (mr *MockFilesMockRecorder) InitStorageUploaderWorkers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitStorageUploaderWorkers", reflect.TypeOf((*MockFiles)(nil).InitStorageUploaderWorkers), ctx)
}

// Save mocks base method.
func (m *MockFiles) Save(ctx context.Context, file domain.File) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, file)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockFilesMockRecorder) Save(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFiles)(nil).Save), ctx, file)
}

// UpdateStatus mocks base method.
func (m *MockFiles) UpdateStatus(ctx context.Context, fileName string, status domain.FileStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, fileName, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFilesMockRecorder) UpdateStatus(ctx, fileName, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFiles)(nil).UpdateStatus), ctx, fileName, status)
}

// UploadAndSaveFile mocks base method.
func (m *MockFiles) UploadAndSaveFile(ctx context.Context, file domain.File) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAndSaveFile", ctx, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAndSaveFile indicates an expected call of UploadAndSaveFile.
func (mr *MockFilesMockRecorder) UploadAndSaveFile(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAndSaveFile", reflect.TypeOf((*MockFiles)(nil).UploadAndSaveFile), ctx, file)
}

// MockEmails is a mock of Emails interface.
type MockEmails struct {
	ctrl     *gomock.Controller
	recorder *MockEmailsMockRecorder
}

// MockEmailsMockRecorder is the mock recorder for MockEmails.
type MockEmailsMockRecorder struct {
	mock *MockEmails
}

// NewMockEmails creates a new mock instance.
func NewMockEmails(ctrl *gomock.Controller) *MockEmails {
	mock := &MockEmails{ctrl: ctrl}
	mock.recorder = &MockEmailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmails) EXPECT() *MockEmailsMockRecorder {
	return m.recorder
}

// AddStudentToList mocks base method.
func (m *MockEmails) AddStudentToList(ctx context.Context, email, name string, schoolID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStudentToList", ctx, email, name, schoolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStudentToList indicates an expected call of AddStudentToList.
func (mr *MockEmailsMockRecorder) AddStudentToList(ctx, email, name, schoolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStudentToList", reflect.TypeOf((*MockEmails)(nil).AddStudentToList), ctx, email, name, schoolID)
}

// SendStudentPurchaseSuccessfulEmail mocks base method.
func (m *MockEmails) SendStudentPurchaseSuccessfulEmail(arg0 service.StudentPurchaseSuccessfulEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendStudentPurchaseSuccessfulEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendStudentPurchaseSuccessfulEmail indicates an expected call of SendStudentPurchaseSuccessfulEmail.
func (mr *MockEmailsMockRecorder) SendStudentPurchaseSuccessfulEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStudentPurchaseSuccessfulEmail", reflect.TypeOf((*MockEmails)(nil).SendStudentPurchaseSuccessfulEmail), arg0)
}

// SendStudentVerificationEmail mocks base method.
func (m *MockEmails) SendStudentVerificationEmail(arg0 service.VerificationEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendStudentVerificationEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendStudentVerificationEmail indicates an expected call of SendStudentVerificationEmail.
func (mr *MockEmailsMockRecorder) SendStudentVerificationEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStudentVerificationEmail", reflect.TypeOf((*MockEmails)(nil).SendStudentVerificationEmail), arg0)
}

// SendUserVerificationEmail mocks base method.
func (m *MockEmails) SendUserVerificationEmail(arg0 service.VerificationEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUserVerificationEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUserVerificationEmail indicates an expected call of SendUserVerificationEmail.
func (mr *MockEmailsMockRecorder) SendUserVerificationEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUserVerificationEmail", reflect.TypeOf((*MockEmails)(nil).SendUserVerificationEmail), arg0)
}

// MockCourses is a mock of Courses interface.
type MockCourses struct {
	ctrl     *gomock.Controller
	recorder *MockCoursesMockRecorder
}

// MockCoursesMockRecorder is the mock recorder for MockCourses.
type MockCoursesMockRecorder struct {
	mock *MockCourses
}

// NewMockCourses creates a new mock instance.
func NewMockCourses(ctrl *gomock.Controller) *MockCourses {
	mock := &MockCourses{ctrl: ctrl}
	mock.recorder = &MockCoursesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourses) EXPECT() *MockCoursesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourses) Create(ctx context.Context, schoolID uint, name string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schoolID, name)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCoursesMockRecorder) Create(ctx, schoolID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourses)(nil).Create), ctx, schoolID, name)
}

// Delete mocks base method.
func (m *MockCourses) Delete(ctx context.Context, schoolID, courseID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, courseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCoursesMockRecorder) Delete(ctx, schoolID, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCourses)(nil).Delete), ctx, schoolID, courseID)
}

// Update mocks base method.
func (m *MockCourses) Update(ctx context.Context, inp service.UpdateCourseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCoursesMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourses)(nil).Update), ctx, inp)
}

// MockPromoCodes is a mock of PromoCodes interface.
type MockPromoCodes struct {
	ctrl     *gomock.Controller
	recorder *MockPromoCodesMockRecorder
}

// MockPromoCodesMockRecorder is the mock recorder for MockPromoCodes.
type MockPromoCodesMockRecorder struct {
	mock *MockPromoCodes
}

// NewMockPromoCodes creates a new mock instance.
func NewMockPromoCodes(ctrl *gomock.Controller) *MockPromoCodes {
	mock := &MockPromoCodes{ctrl: ctrl}
	mock.recorder = &MockPromoCodesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoCodes) EXPECT() *MockPromoCodesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPromoCodes) Create(ctx context.Context, inp service.CreatePromoCodeInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPromoCodesMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPromoCodes)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockPromoCodes) Delete(ctx context.Context, schoolID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPromoCodesMockRecorder) Delete(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPromoCodes)(nil).Delete), ctx, schoolID, id)
}

// GetByCode mocks base method.
func (m *MockPromoCodes) GetByCode(ctx context.Context, schoolID uint, code string) (domain.PromoCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, schoolID, code)
	ret0, _ := ret[0].(domain.PromoCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPromoCodesMockRecorder) GetByCode(ctx, schoolID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPromoCodes)(nil).GetByCode), ctx, schoolID, code)
}

// GetById mocks base method.
func (m *MockPromoCodes) GetById(ctx context.Context, schoolID, id uint) (domain.PromoCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, schoolID, id)
	ret0, _ := ret[0].(domain.PromoCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPromoCodesMockRecorder) GetById(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPromoCodes)(nil).GetById), ctx, schoolID, id)
}

// GetBySchool mocks base method.
func (m *MockPromoCodes) GetBySchool(ctx context.Context, schoolID uint) ([]domain.PromoCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchool", ctx, schoolID)
	ret0, _ := ret[0].([]domain.PromoCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySchool indicates an expected call of GetBySchool.
func (mr *MockPromoCodesMockRecorder) GetBySchool(ctx, schoolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchool", reflect.TypeOf((*MockPromoCodes)(nil).GetBySchool), ctx, schoolID)
}

// Update mocks base method.
func (m *MockPromoCodes) Update(ctx context.Context, inp domain.UpdatePromoCodeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPromoCodesMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPromoCodes)(nil).Update), ctx, inp)
}

// MockOffers is a mock of Offers interface.
type MockOffers struct {
	ctrl     *gomock.Controller
	recorder *MockOffersMockRecorder
}

// MockOffersMockRecorder is the mock recorder for MockOffers.
type MockOffersMockRecorder struct {
	mock *MockOffers
}

// NewMockOffers creates a new mock instance.
func NewMockOffers(ctrl *gomock.Controller) *MockOffers {
	mock := &MockOffers{ctrl: ctrl}
	mock.recorder = &MockOffersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOffers) EXPECT() *MockOffersMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOffers) Create(ctx context.Context, inp service.CreateOfferInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOffersMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOffers)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockOffers) Delete(ctx context.Context, schoolID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOffersMockRecorder) Delete(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOffers)(nil).Delete), ctx, schoolID, id)
}

// GetAll mocks base method.
func (m *MockOffers) GetAll(ctx context.Context, schoolID uint) ([]domain.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, schoolID)
	ret0, _ := ret[0].([]domain.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOffersMockRecorder) GetAll(ctx, schoolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOffers)(nil).GetAll), ctx, schoolID)
}

// GetByCourse mocks base method.
func (m *MockOffers) GetByCourse(ctx context.Context, courseID uint) ([]domain.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCourse", ctx, courseID)
	ret0, _ := ret[0].([]domain.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCourse indicates an expected call of GetByCourse.
func (mr *MockOffersMockRecorder) GetByCourse(ctx, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCourse", reflect.TypeOf((*MockOffers)(nil).GetByCourse), ctx, courseID)
}

// GetById mocks base method.
func (m *MockOffers) GetById(ctx context.Context, id uint) (domain.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(domain.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOffersMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOffers)(nil).GetById), ctx, id)
}

// GetByIds mocks base method.
func (m *MockOffers) GetByIds(ctx context.Context, ids []uint) ([]domain.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockOffersMockRecorder) GetByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockOffers)(nil).GetByIds), ctx, ids)
}

// GetByModule mocks base method.
func (m *MockOffers) GetByModule(ctx context.Context, schoolID, moduleID uint) ([]domain.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModule", ctx, schoolID, moduleID)
	ret0, _ := ret[0].([]domain.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByModule indicates an expected call of GetByModule.
func (mr *MockOffersMockRecorder) GetByModule(ctx, schoolID, moduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModule", reflect.TypeOf((*MockOffers)(nil).GetByModule), ctx, schoolID, moduleID)
}

// Update mocks base method.
func (m *MockOffers) Update(ctx context.Context, inp service.UpdateOfferInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOffersMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOffers)(nil).Update), ctx, inp)
}

// MockModules is a mock of Modules interface.
type MockModules struct {
	ctrl     *gomock.Controller
	recorder *MockModulesMockRecorder
}

// MockModulesMockRecorder is the mock recorder for MockModules.
type MockModulesMockRecorder struct {
	mock *MockModules
}

// NewMockModules creates a new mock instance.
func NewMockModules(ctrl *gomock.Controller) *MockModules {
	mock := &MockModules{ctrl: ctrl}
	mock.recorder = &MockModulesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModules) EXPECT() *MockModulesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockModules) Create(ctx context.Context, inp service.CreateModuleInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockModulesMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModules)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockModules) Delete(ctx context.Context, schoolID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockModulesMockRecorder) Delete(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModules)(nil).Delete), ctx, schoolID, id)
}

// DeleteByCourse mocks base method.
func (m *MockModules) DeleteByCourse(ctx context.Context, schoolID, courseID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCourse", ctx, schoolID, courseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCourse indicates an expected call of DeleteByCourse.
func (mr *MockModulesMockRecorder) DeleteByCourse(ctx, schoolID, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCourse", reflect.TypeOf((*MockModules)(nil).DeleteByCourse), ctx, schoolID, courseID)
}

// GetByCourseId mocks base method.
func (m *MockModules) GetByCourseId(ctx context.Context, courseID uint) ([]domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCourseId", ctx, courseID)
	ret0, _ := ret[0].([]domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCourseId indicates an expected call of GetByCourseId.
func (mr *MockModulesMockRecorder) GetByCourseId(ctx, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCourseId", reflect.TypeOf((*MockModules)(nil).GetByCourseId), ctx, courseID)
}

// GetById mocks base method.
func (m *MockModules) GetById(ctx context.Context, moduleID uint) (domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, moduleID)
	ret0, _ := ret[0].(domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockModulesMockRecorder) GetById(ctx, moduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockModules)(nil).GetById), ctx, moduleID)
}

// GetByLesson mocks base method.
func (m *MockModules) GetByLesson(ctx context.Context, lessonID uint) (domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLesson", ctx, lessonID)
	ret0, _ := ret[0].(domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLesson indicates an expected call of GetByLesson.
func (mr *MockModulesMockRecorder) GetByLesson(ctx, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLesson", reflect.TypeOf((*MockModules)(nil).GetByLesson), ctx, lessonID)
}

// GetByPackages mocks base method.
func (m *MockModules) GetByPackages(ctx context.Context, packageIDs []uint) ([]domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPackages", ctx, packageIDs)
	ret0, _ := ret[0].([]domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPackages indicates an expected call of GetByPackages.
func (mr *MockModulesMockRecorder) GetByPackages(ctx, packageIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPackages", reflect.TypeOf((*MockModules)(nil).GetByPackages), ctx, packageIDs)
}

// GetPublishedByCourseId mocks base method.
func (m *MockModules) GetPublishedByCourseId(ctx context.Context, courseID uint) ([]domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedByCourseId", ctx, courseID)
	ret0, _ := ret[0].([]domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedByCourseId indicates an expected call of GetPublishedByCourseId.
func (mr *MockModulesMockRecorder) GetPublishedByCourseId(ctx, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedByCourseId", reflect.TypeOf((*MockModules)(nil).GetPublishedByCourseId), ctx, courseID)
}

// GetWithContent mocks base method.
func (m *MockModules) GetWithContent(ctx context.Context, moduleID uint) (domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithContent", ctx, moduleID)
	ret0, _ := ret[0].(domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithContent indicates an expected call of GetWithContent.
func (mr *MockModulesMockRecorder) GetWithContent(ctx, moduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithContent", reflect.TypeOf((*MockModules)(nil).GetWithContent), ctx, moduleID)
}

// Update mocks base method.
func (m *MockModules) Update(ctx context.Context, inp service.UpdateModuleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockModulesMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModules)(nil).Update), ctx, inp)
}

// MockLessons is a mock of Lessons interface.
type MockLessons struct {
	ctrl     *gomock.Controller
	recorder *MockLessonsMockRecorder
}

// MockLessonsMockRecorder is the mock recorder for MockLessons.
type MockLessonsMockRecorder struct {
	mock *MockLessons
}

// NewMockLessons creates a new mock instance.
func NewMockLessons(ctrl *gomock.Controller) *MockLessons {
	mock := &MockLessons{ctrl: ctrl}
	mock.recorder = &MockLessonsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessons) EXPECT() *MockLessonsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLessons) Create(ctx context.Context, inp service.AddLessonInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLessonsMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLessons)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockLessons) Delete(ctx context.Context, schoolID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLessonsMockRecorder) Delete(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLessons)(nil).Delete), ctx, schoolID, id)
}

// DeleteContent mocks base method.
func (m *MockLessons) DeleteContent(ctx context.Context, schoolID uint, lessonIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContent", ctx, schoolID, lessonIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContent indicates an expected call of DeleteContent.
func (mr *MockLessonsMockRecorder) DeleteContent(ctx, schoolID, lessonIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContent", reflect.TypeOf((*MockLessons)(nil).DeleteContent), ctx, schoolID, lessonIDs)
}

// GetById mocks base method.
func (m *MockLessons) GetById(ctx context.Context, lessonID uint) (domain.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, lessonID)
	ret0, _ := ret[0].(domain.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockLessonsMockRecorder) GetById(ctx, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockLessons)(nil).GetById), ctx, lessonID)
}

// Update mocks base method.
func (m *MockLessons) Update(ctx context.Context, inp service.UpdateLessonInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLessonsMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLessons)(nil).Update), ctx, inp)
}

// MockPackages is a mock of Packages interface.
type MockPackages struct {
	ctrl     *gomock.Controller
	recorder *MockPackagesMockRecorder
}

// MockPackagesMockRecorder is the mock recorder for MockPackages.
type MockPackagesMockRecorder struct {
	mock *MockPackages
}

// NewMockPackages creates a new mock instance.
func NewMockPackages(ctrl *gomock.Controller) *MockPackages {
	mock := &MockPackages{ctrl: ctrl}
	mock.recorder = &MockPackagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackages) EXPECT() *MockPackagesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPackages) Create(ctx context.Context, inp service.CreatePackageInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPackagesMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPackages)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockPackages) Delete(ctx context.Context, schoolID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPackagesMockRecorder) Delete(ctx, schoolID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPackages)(nil).Delete), ctx, schoolID, id)
}

// GetByCourse mocks base method.
func (m *MockPackages) GetByCourse(ctx context.Context, courseID uint) ([]domain.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCourse", ctx, courseID)
	ret0, _ := ret[0].([]domain.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCourse indicates an expected call of GetByCourse.
func (mr *MockPackagesMockRecorder) GetByCourse(ctx, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCourse", reflect.TypeOf((*MockPackages)(nil).GetByCourse), ctx, courseID)
}

// GetById mocks base method.
func (m *MockPackages) GetById(ctx context.Context, id uint) (domain.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(domain.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPackagesMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPackages)(nil).GetById), ctx, id)
}

// GetByIds mocks base method.
func (m *MockPackages) GetByIds(ctx context.Context, ids []uint) ([]domain.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockPackagesMockRecorder) GetByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockPackages)(nil).GetByIds), ctx, ids)
}

// Update mocks base method.
func (m *MockPackages) Update(ctx context.Context, inp service.UpdatePackageInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPackagesMockRecorder) Update(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPackages)(nil).Update), ctx, inp)
}

// MockOrders is a mock of Orders interface.
type MockOrders struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersMockRecorder
}

// MockOrdersMockRecorder is the mock recorder for MockOrders.
type MockOrdersMockRecorder struct {
	mock *MockOrders
}

// NewMockOrders creates a new mock instance.
func NewMockOrders(ctrl *gomock.Controller) *MockOrders {
	mock := &MockOrders{ctrl: ctrl}
	mock.recorder = &MockOrdersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrders) EXPECT() *MockOrdersMockRecorder {
	return m.recorder
}

// AddTransaction mocks base method.
func (m *MockOrders) AddTransaction(ctx context.Context, id uint, transaction domain.Transaction) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransaction", ctx, id, transaction)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTransaction indicates an expected call of AddTransaction.
func (mr *MockOrdersMockRecorder) AddTransaction(ctx, id, transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransaction", reflect.TypeOf((*MockOrders)(nil).AddTransaction), ctx, id, transaction)
}

// Create mocks base method.
func (m *MockOrders) Create(ctx context.Context, studentID, offerID, promocodeID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, studentID, offerID, promocodeID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrdersMockRecorder) Create(ctx, studentID, offerID, promocodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrders)(nil).Create), ctx, studentID, offerID, promocodeID)
}

// GetById mocks base method.
func (m *MockOrders) GetById(ctx context.Context, id uint) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOrdersMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOrders)(nil).GetById), ctx, id)
}

// GetBySchool mocks base method.
func (m *MockOrders) GetBySchool(ctx context.Context, schoolID uint, query domain.GetOrdersQuery) ([]domain.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchool", ctx, schoolID, query)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBySchool indicates an expected call of GetBySchool.
func (mr *MockOrdersMockRecorder) GetBySchool(ctx, schoolID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchool", reflect.TypeOf((*MockOrders)(nil).GetBySchool), ctx, schoolID, query)
}

// SetStatus mocks base method.
func (m *MockOrders) SetStatus(ctx context.Context, id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockOrdersMockRecorder) SetStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockOrders)(nil).SetStatus), ctx, id, status)
}

// MockPayments is a mock of Payments interface.
type MockPayments struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsMockRecorder
}

// MockPaymentsMockRecorder is the mock recorder for MockPayments.
type MockPaymentsMockRecorder struct {
	mock *MockPayments
}

// NewMockPayments creates a new mock instance.
func NewMockPayments(ctrl *gomock.Controller) *MockPayments {
	mock := &MockPayments{ctrl: ctrl}
	mock.recorder = &MockPaymentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayments) EXPECT() *MockPaymentsMockRecorder {
	return m.recorder
}

// GeneratePaymentLink mocks base method.
func (m *MockPayments) GeneratePaymentLink(ctx context.Context, orderID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePaymentLink", ctx, orderID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePaymentLink indicates an expected call of GeneratePaymentLink.
func (mr *MockPaymentsMockRecorder) GeneratePaymentLink(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePaymentLink", reflect.TypeOf((*MockPayments)(nil).GeneratePaymentLink), ctx, orderID)
}

// ProcessTransaction mocks base method.
func (m *MockPayments) ProcessTransaction(ctx context.Context, callback interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTransaction", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTransaction indicates an expected call of ProcessTransaction.
func (mr *MockPaymentsMockRecorder) ProcessTransaction(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTransaction", reflect.TypeOf((*MockPayments)(nil).ProcessTransaction), ctx, callback)
}

// MockSurveys is a mock of Surveys interface.
type MockSurveys struct {
	ctrl     *gomock.Controller
	recorder *MockSurveysMockRecorder
}

// MockSurveysMockRecorder is the mock recorder for MockSurveys.
type MockSurveysMockRecorder struct {
	mock *MockSurveys
}

// NewMockSurveys creates a new mock instance.
func NewMockSurveys(ctrl *gomock.Controller) *MockSurveys {
	mock := &MockSurveys{ctrl: ctrl}
	mock.recorder = &MockSurveysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSurveys) EXPECT() *MockSurveysMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSurveys) Create(ctx context.Context, inp service.CreateSurveyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSurveysMockRecorder) Create(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSurveys)(nil).Create), ctx, inp)
}

// Delete mocks base method.
func (m *MockSurveys) Delete(ctx context.Context, schoolID, moduleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schoolID, moduleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSurveysMockRecorder) Delete(ctx, schoolID, moduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSurveys)(nil).Delete), ctx, schoolID, moduleID)
}

// GetResultsByModule mocks base method.
func (m *MockSurveys) GetResultsByModule(ctx context.Context, moduleID uint, pagination *domain.PaginationQuery) ([]domain.SurveyResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultsByModule", ctx, moduleID, pagination)
	ret0, _ := ret[0].([]domain.SurveyResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetResultsByModule indicates an expected call of GetResultsByModule.
func (mr *MockSurveysMockRecorder) GetResultsByModule(ctx, moduleID, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultsByModule", reflect.TypeOf((*MockSurveys)(nil).GetResultsByModule), ctx, moduleID, pagination)
}

// GetStudentResults mocks base method.
func (m *MockSurveys) GetStudentResults(ctx context.Context, moduleID, studentID uint) (domain.SurveyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentResults", ctx, moduleID, studentID)
	ret0, _ := ret[0].(domain.SurveyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentResults indicates an expected call of GetStudentResults.
func (mr *MockSurveysMockRecorder) GetStudentResults(ctx, moduleID, studentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentResults", reflect.TypeOf((*MockSurveys)(nil).GetStudentResults), ctx, moduleID, studentID)
}

// SaveStudentAnswers mocks base method.
func (m *MockSurveys) SaveStudentAnswers(ctx context.Context, inp service.SaveStudentAnswersInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStudentAnswers", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStudentAnswers indicates an expected call of SaveStudentAnswers.
func (mr *MockSurveysMockRecorder) SaveStudentAnswers(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudentAnswers", reflect.TypeOf((*MockSurveys)(nil).SaveStudentAnswers), ctx, inp)
}
